// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// WARNING! Do not edit this file manually, your changes will be overwritten.

#pragma once

#ifndef GENERATEDPASSWORDOBJECT_H
#define GENERATEDPASSWORDOBJECT_H

#include "PasswordSchema.h"

namespace graphql::password::object {
namespace methods::GeneratedPasswordHas {

template <class TImpl>
concept getValueWithParams = requires (TImpl impl, service::FieldParams params)
{
	{ service::AwaitableScalar<std::string> { impl.getValue(std::move(params)) } };
};

template <class TImpl>
concept getValue = requires (TImpl impl)
{
	{ service::AwaitableScalar<std::string> { impl.getValue() } };
};

template <class TImpl>
concept getLengthWithParams = requires (TImpl impl, service::FieldParams params)
{
	{ service::AwaitableScalar<int> { impl.getLength(std::move(params)) } };
};

template <class TImpl>
concept getLength = requires (TImpl impl)
{
	{ service::AwaitableScalar<int> { impl.getLength() } };
};

template <class TImpl>
concept getStrengthWithParams = requires (TImpl impl, service::FieldParams params)
{
	{ service::AwaitableScalar<std::string> { impl.getStrength(std::move(params)) } };
};

template <class TImpl>
concept getStrength = requires (TImpl impl)
{
	{ service::AwaitableScalar<std::string> { impl.getStrength() } };
};

template <class TImpl>
concept beginSelectionSet = requires (TImpl impl, const service::SelectionSetParams params)
{
	{ impl.beginSelectionSet(params) };
};

template <class TImpl>
concept endSelectionSet = requires (TImpl impl, const service::SelectionSetParams params)
{
	{ impl.endSelectionSet(params) };
};

} // namespace methods::GeneratedPasswordHas

class [[nodiscard("unnecessary construction")]] GeneratedPassword final
	: public service::Object
{
private:
	[[nodiscard("unnecessary call")]] service::AwaitableResolver resolveValue(service::ResolverParams&& params) const;
	[[nodiscard("unnecessary call")]] service::AwaitableResolver resolveLength(service::ResolverParams&& params) const;
	[[nodiscard("unnecessary call")]] service::AwaitableResolver resolveStrength(service::ResolverParams&& params) const;

	[[nodiscard("unnecessary call")]] service::AwaitableResolver resolve_typename(service::ResolverParams&& params) const;

	struct [[nodiscard("unnecessary construction")]] Concept
	{
		virtual ~Concept() = default;

		virtual void beginSelectionSet(const service::SelectionSetParams& params) const = 0;
		virtual void endSelectionSet(const service::SelectionSetParams& params) const = 0;

		[[nodiscard("unnecessary call")]] virtual service::AwaitableScalar<std::string> getValue(service::FieldParams&& params) const = 0;
		[[nodiscard("unnecessary call")]] virtual service::AwaitableScalar<int> getLength(service::FieldParams&& params) const = 0;
		[[nodiscard("unnecessary call")]] virtual service::AwaitableScalar<std::string> getStrength(service::FieldParams&& params) const = 0;
	};

	template <class T>
	struct [[nodiscard("unnecessary construction")]] Model final
		: Concept
	{
		explicit Model(std::shared_ptr<T> pimpl) noexcept
			: _pimpl { std::move(pimpl) }
		{
		}

		[[nodiscard("unnecessary call")]] service::AwaitableScalar<std::string> getValue(service::FieldParams&& params) const override
		{
			if constexpr (methods::GeneratedPasswordHas::getValueWithParams<T>)
			{
				return { _pimpl->getValue(std::move(params)) };
			}
			else
			{
				static_assert(methods::GeneratedPasswordHas::getValue<T>, R"msg(GeneratedPassword::getValue is not implemented)msg");
				return { _pimpl->getValue() };
			}
		}

		[[nodiscard("unnecessary call")]] service::AwaitableScalar<int> getLength(service::FieldParams&& params) const override
		{
			if constexpr (methods::GeneratedPasswordHas::getLengthWithParams<T>)
			{
				return { _pimpl->getLength(std::move(params)) };
			}
			else
			{
				static_assert(methods::GeneratedPasswordHas::getLength<T>, R"msg(GeneratedPassword::getLength is not implemented)msg");
				return { _pimpl->getLength() };
			}
		}

		[[nodiscard("unnecessary call")]] service::AwaitableScalar<std::string> getStrength(service::FieldParams&& params) const override
		{
			if constexpr (methods::GeneratedPasswordHas::getStrengthWithParams<T>)
			{
				return { _pimpl->getStrength(std::move(params)) };
			}
			else
			{
				static_assert(methods::GeneratedPasswordHas::getStrength<T>, R"msg(GeneratedPassword::getStrength is not implemented)msg");
				return { _pimpl->getStrength() };
			}
		}

		void beginSelectionSet(const service::SelectionSetParams& params) const override
		{
			if constexpr (methods::GeneratedPasswordHas::beginSelectionSet<T>)
			{
				_pimpl->beginSelectionSet(params);
			}
		}

		void endSelectionSet(const service::SelectionSetParams& params) const override
		{
			if constexpr (methods::GeneratedPasswordHas::endSelectionSet<T>)
			{
				_pimpl->endSelectionSet(params);
			}
		}

	private:
		const std::shared_ptr<T> _pimpl;
	};

	explicit GeneratedPassword(std::unique_ptr<const Concept> pimpl) noexcept;

	[[nodiscard("unnecessary call")]] service::TypeNames getTypeNames() const noexcept;
	[[nodiscard("unnecessary call")]] service::ResolverMap getResolvers() const noexcept;

	void beginSelectionSet(const service::SelectionSetParams& params) const override;
	void endSelectionSet(const service::SelectionSetParams& params) const override;

	const std::unique_ptr<const Concept> _pimpl;

public:
	template <class T>
	explicit GeneratedPassword(std::shared_ptr<T> pimpl) noexcept
		: GeneratedPassword { std::unique_ptr<const Concept> { std::make_unique<Model<T>>(std::move(pimpl)) } }
	{
	}

	[[nodiscard("unnecessary call")]] static constexpr std::string_view getObjectType() noexcept
	{
		return { R"gql(GeneratedPassword)gql" };
	}
};

} // namespace graphql::password::object

#endif // GENERATEDPASSWORDOBJECT_H
