// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// WARNING! Do not edit this file manually, your changes will be overwritten.

#pragma once

#ifndef MUTATIONOBJECT_H
#define MUTATIONOBJECT_H

#include "PasswordSchema.h"

namespace graphql::password::object {
namespace methods::MutationHas {

template <class TImpl>
concept applyGeneratePasswordWithParams = requires (TImpl impl, service::FieldParams params, GeneratePasswordInput inputArg)
{
	{ service::AwaitableObject<std::shared_ptr<GeneratedPassword>> { impl.applyGeneratePassword(std::move(params), std::move(inputArg)) } };
};

template <class TImpl>
concept applyGeneratePassword = requires (TImpl impl, GeneratePasswordInput inputArg)
{
	{ service::AwaitableObject<std::shared_ptr<GeneratedPassword>> { impl.applyGeneratePassword(std::move(inputArg)) } };
};

template <class TImpl>
concept beginSelectionSet = requires (TImpl impl, const service::SelectionSetParams params)
{
	{ impl.beginSelectionSet(params) };
};

template <class TImpl>
concept endSelectionSet = requires (TImpl impl, const service::SelectionSetParams params)
{
	{ impl.endSelectionSet(params) };
};

} // namespace methods::MutationHas

class [[nodiscard("unnecessary construction")]] Mutation final
	: public service::Object
{
private:
	[[nodiscard("unnecessary call")]] service::AwaitableResolver resolveGeneratePassword(service::ResolverParams&& params) const;

	[[nodiscard("unnecessary call")]] service::AwaitableResolver resolve_typename(service::ResolverParams&& params) const;

	struct [[nodiscard("unnecessary construction")]] Concept
	{
		virtual ~Concept() = default;

		virtual void beginSelectionSet(const service::SelectionSetParams& params) const = 0;
		virtual void endSelectionSet(const service::SelectionSetParams& params) const = 0;

		[[nodiscard("unnecessary call")]] virtual service::AwaitableObject<std::shared_ptr<GeneratedPassword>> applyGeneratePassword(service::FieldParams&& params, GeneratePasswordInput&& inputArg) const = 0;
	};

	template <class T>
	struct [[nodiscard("unnecessary construction")]] Model final
		: Concept
	{
		explicit Model(std::shared_ptr<T> pimpl) noexcept
			: _pimpl { std::move(pimpl) }
		{
		}

		[[nodiscard("unnecessary call")]] service::AwaitableObject<std::shared_ptr<GeneratedPassword>> applyGeneratePassword(service::FieldParams&& params, GeneratePasswordInput&& inputArg) const override
		{
			if constexpr (methods::MutationHas::applyGeneratePasswordWithParams<T>)
			{
				return { _pimpl->applyGeneratePassword(std::move(params), std::move(inputArg)) };
			}
			else
			{
				static_assert(methods::MutationHas::applyGeneratePassword<T>, R"msg(Mutation::applyGeneratePassword is not implemented)msg");
				return { _pimpl->applyGeneratePassword(std::move(inputArg)) };
			}
		}

		void beginSelectionSet(const service::SelectionSetParams& params) const override
		{
			if constexpr (methods::MutationHas::beginSelectionSet<T>)
			{
				_pimpl->beginSelectionSet(params);
			}
		}

		void endSelectionSet(const service::SelectionSetParams& params) const override
		{
			if constexpr (methods::MutationHas::endSelectionSet<T>)
			{
				_pimpl->endSelectionSet(params);
			}
		}

	private:
		const std::shared_ptr<T> _pimpl;
	};

	explicit Mutation(std::unique_ptr<const Concept> pimpl) noexcept;

	[[nodiscard("unnecessary call")]] service::TypeNames getTypeNames() const noexcept;
	[[nodiscard("unnecessary call")]] service::ResolverMap getResolvers() const noexcept;

	void beginSelectionSet(const service::SelectionSetParams& params) const override;
	void endSelectionSet(const service::SelectionSetParams& params) const override;

	const std::unique_ptr<const Concept> _pimpl;

public:
	template <class T>
	explicit Mutation(std::shared_ptr<T> pimpl) noexcept
		: Mutation { std::unique_ptr<const Concept> { std::make_unique<Model<T>>(std::move(pimpl)) } }
	{
	}

	[[nodiscard("unnecessary call")]] static constexpr std::string_view getObjectType() noexcept
	{
		return { R"gql(Mutation)gql" };
	}
};

} // namespace graphql::password::object

#endif // MUTATIONOBJECT_H
